Trying to fix exit codes 2: returned old main_loop function
Trying to fix exit codes 3: returned old handle_input function


Trying to fix exit codes 4: Reverting some small changes


Trying to fix exit codes 5: Replace get_value_from_key with new anas version


Trying to fix exit codes 6: Replace expand_value with anas version


Trying to fix exit codes 7: Replace init_infile with anas version


Trying to fix exit codes 8: reverted change in env.c


Trying to fix exit codes 9: reverted change in expandvalue.c


Trying to fix exit codes 10: revert change in get_cmd function


Trying to fix exit codes 11: revert changes to init_heredoc function


Trying to fix exit codes 12: replace entire quotes.c with old version


Trying to fix exit codes 13: replaced entire pipes.c with old version


Trying to fix exit codes 14: replaced entire bulitins.c file with anas version


Trying to fix exit codes 15: replaced entire tokens.c with old version


Fixing exit codes 16: Replaced entire main.c. They're working now


Revert "Trying to fix exit codes 15: replaced entire tokens.c with old version"

This reverts commit 15121425c640e568f5e3ab8e4136952d4461eb52.
Revert "Trying to fix exit codes 14: replaced entire bulitins.c file with anas version"

This reverts commit bc32e8f3377e49c22ec3beb4299ac84d989ece0a.

Revert "Trying to fix exit codes 13: replaced entire pipes.c with old version"

This reverts commit 01e6c0ae04986c32d3b16aa0885200998401d7b8.

Revert "Trying to fix exit codes 12: replace entire quotes.c with old version"

This reverts commit 863874a96e6a2c599b1dab6b2596ed0277b513d5.

Revert "Trying to fix exit codes 11: revert changes to init_heredoc function"

This reverts commit ea9bb458fc245e763827f39f07bb28b84b6d4daa.
Revert "Trying to fix exit codes 10: revert change in get_cmd function"

This reverts commit 1ee1326b8a300fba9a9800ce8c29dcf780400654.

Revert "Trying to fix exit codes 9: reverted change in expandvalue.c"

This reverts commit 57ad85bc07f8aa5e8c223784154d7d26f0108fde.

Revert "Trying to fix exit codes 8: reverted change in env.c"

This reverts commit 14f5ba3b3ee81cc2584ab2a682107b61cbded166.

Revert "Trying to fix exit codes 7: Replace init_infile with anas version"

This reverts commit 2516e7bad1520a91f024128f5622066ca203c657.

Revert "Trying to fix exit codes 6: Replace expand_value with anas version"

This reverts commit d82489fab0d09898b8b48773e42e57caa83738ea.

Revert "Trying to fix exit codes 5: Replace get_value_from_key with new anas version"

This reverts commit 4ec5e493659636543069fe9b3a74aaad63ee0e4a.

Revert "Trying to fix exit codes 4: Reverting some small changes"

This reverts commit b833c2eaf5df5455a055980c55cbac925e8d62a9.

Revert "Trying to fix exit codes 3: returned old handle_input function"

This reverts commit 076951d60e5913abac842de34c0354c8bb6c4b1e.

Revert "Trying to fix exit codes 2: returned old main_loop function"

Exit codes are still working. reset_term_signals() seems to be to blame.
Added new problems to list of test cases

diff --git a/problems_and_test_cases b/problems_and_test_cases
--- a/problems_and_test_cases
+++ b/problems_and_test_cases
@@ -2,9 +2,16 @@
 not working:
 ****************/
 
-echo $USER'$USER'$USER		(outputs an extra space that shouldn't be there)
-many many leaks
-any command with a pipe also seems to loak
+echo $foo					(segfaults)
+echo $?						(leaks)
+echo $?						(does not output '0' if it is the first command being executed, instead outputs some random value)
+export a=1 | cat 			(does not behave like bash, bash does not export the variable and does not block/'hang')
+grep -Hirn "parse error" .	(quotes problem, outputs lines that don't contain parse error)
+echo "'$USER'"				(should output adinari or slakner, but it just outputs a single ' (single quote))
+
+minishell sometimes 'hangs' and does not display the next prompt after input. Seems to happen after an unclose quotes error, but I'm not sure.
+"" | "" | ""
+
 dprintf is a forbidden function
 perror is a forbidden function
 ""							(should output "command not found")
